//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subeditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subeditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files .
        /// </summary>
        internal static string DscAllSupported {
            get {
                return ResourceManager.GetString("DscAllSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced SubStation Alpha.
        /// </summary>
        internal static string DscASS {
            get {
                return ResourceManager.GetString("DscASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicroDVD Subtitle File.
        /// </summary>
        internal static string DscMicroDVD {
            get {
                return ResourceManager.GetString("DscMicroDVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubStation Alpha.
        /// </summary>
        internal static string DscSSA {
            get {
                return ResourceManager.GetString("DscSSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubRip format.
        /// </summary>
        internal static string DscSubRip {
            get {
                return ResourceManager.GetString("DscSubRip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMPlayer subtitles.
        /// </summary>
        internal static string DscTMPlayer {
            get {
                return ResourceManager.GetString("DscTMPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown file format.
        /// </summary>
        internal static string DscUnresolved {
            get {
                return ResourceManager.GetString("DscUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        internal static string Encoding1200 {
            get {
                return ResourceManager.GetString("Encoding1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Big Endian.
        /// </summary>
        internal static string Encoding1201 {
            get {
                return ResourceManager.GetString("Encoding1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European.
        /// </summary>
        internal static string Encoding1250 {
            get {
                return ResourceManager.GetString("Encoding1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European.
        /// </summary>
        internal static string Encoding1252 {
            get {
                return ResourceManager.GetString("Encoding1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        internal static string Encoding65001 {
            get {
                return ResourceManager.GetString("Encoding65001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add two control points with the same orginal timing..
        /// </summary>
        internal static string MsgSyncPointOrginalTimingWrong {
            get {
                return ResourceManager.GetString("MsgSyncPointOrginalTimingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subeditor.
        /// </summary>
        internal static string NameApplication {
            get {
                return ResourceManager.GetString("NameApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubeditorMainView.
        /// </summary>
        internal static string NameMainView {
            get {
                return ResourceManager.GetString("NameMainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets\alert.png.
        /// </summary>
        internal static string PathAlertImage {
            get {
                return ResourceManager.GetString("PathAlertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets\AppIcon.ico.
        /// </summary>
        internal static string PathAppIcon {
            get {
                return ResourceManager.GetString("PathAppIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets\error.png.
        /// </summary>
        internal static string PathErrorImage {
            get {
                return ResourceManager.GetString("PathErrorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/projects/app-subeditor/files/bin/versioninfo.xml/download.
        /// </summary>
        internal static string URLVersionInfo {
            get {
                return ResourceManager.GetString("URLVersionInfo", resourceCulture);
            }
        }
    }
}
